### ISSUE TITLE
Does not seem to properly alias 'vengo' command: OS X 10.10.1

### ISSUE THREAD

**Issue by benderTheCrime** [DamnWidget/VenGO#5]
DamnWidget,

Awesome job creating this tool, it is a necessary for me to have an easy tool to spin up Go environments without the added work of managing paths.

I'm using Yosemite, with what appears to be a proper install of VenGO ($HOME/.VenGO/bin/vengo.sh exists) and go version:

go version go1.3.2 darwin/amd64

I've got the vengo.sh properly loading in my bashrc. However, when I hit 'vengo', I get the following error:

$HOME/.VenGO/bin/vengo: No such file or directory

Any thoughts on why this may be?

**Comment by DamnWidget** [comment]
Is the `vengo` binary installed into `~/.VenGO/bin`?

If not, try to install it again using the curl method.

**Comment by benderTheCrime** [comment]
I see,

```bash
Getting VenGO binary... go: cannot find GOROOT directory: /usr/local/bin/go
mv: rename $HOME/go/bin/VenGO to .vengo_installation/bin/vengo: No such file or directory
```

This appears to be a problem with my GOPATH. Thanks for the tip. And again, awesome tool.

**Comment by DamnWidget** [comment]
Did you manage to solve it?

**Comment by benderTheCrime** [comment]
Yeah, I modified my GOPATH and sourced my bashrc, then went back to the repl from the git repo  and installed via:
go get $REPOSITORY 
and copied the vengo files directly into my .VenGO folder.
I didn't run the script from scratch, but I can if you would like, it will produce the same result.

**Comment by DamnWidget** [comment]
Nope, it's ok, I am just glad that you solve it :)
